default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tl_jwt_sample_development

test:
  <<: *default
  database: tl_jwt_sample_test

production:
  <<: *default
  host: <%= Rails.application.credentials.database[:host] %>
  port: <%= Rails.application.credentials.database[:port] %>
  database: tl_jwt_sample_production
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
